export const FOCUS_DEFINITIONS: Record<string, string> = {
  'Kecemasan': 'Rasa khawatir atau takut yang berlebihan dan susah dimatikan. Bisa muncul sebagai panic attacks, ketegangan terus-menerus, atau ketakutan spesifik yang ganggu aktivitas.',
  'Depresi': 'Lebih dari sekadar sedih. Bisa terasa seperti kekosongan, kehilangan semangat untuk hal-hal yang biasanya kamu suka, atau susah bangun di pagi hari.',
  'Trauma': 'Pengalaman berat yang masih "nempel" sampai sekarang — bisa dari masa kecil, hubungan yang menyakitkan, atau kejadian tertentu yang belum selesai diproses.',
  'OCD': 'Pikiran yang berulang-ulang dan susah dihentikan (obsesi), atau dorongan untuk melakukan ritual tertentu supaya cemas mereda (kompulsi).',
  'BPD': 'Emosi yang intens dan cepat berubah, hubungan yang naik-turun drastis, dan rasa takut ditinggal yang dalam.',
  'Relasi Romantis': 'Masalah di hubungan — komunikasi yang tidak nyambung, kepercayaan yang bolong, ketergantungan emosional, atau proses move on setelah putus.',
  'Burnout': 'Kelelahan total — fisik, emosi, dan mental — yang datang dari tekanan atau tanggung jawab yang terlalu berat dalam waktu terlalu lama.',
  'Psikologi Anak': 'Tantangan pada anak: keterlambatan perkembangan, perilaku yang bikin pusing, masalah emosi, atau kesulitan belajar.',
  'Remaja': 'Tekanan di masa remaja — mencari identitas, tekanan sosial, akademik, konflik keluarga, atau navigating life changes yang datang bersamaan.',
  'Keluarga': 'Dinamika keluarga: konflik orang tua dan anak, batas-batas yang belum jelas, pola hubungan yang sudah lama tidak sehat.',
  'Pernikahan': 'Masalah dalam pernikahan: komunikasi yang terasa jauh, kepercayaan yang retak, konflik yang berulang, atau sedang mempertimbangkan jalan ke depan.',
  'Karier': 'Stres kerja, konflik di kantor, merasa stuck atau tidak puas, atau sedang dalam transisi karier yang penuh ketidakpastian.',
  'Regulasi Emosi': 'Kesulitan mengelola emosi — sering meledak, mudah overwhelmed, atau justru sebaliknya: mati rasa dan sulit merasakan apapun.',
  'Stres': 'Tekanan yang terasa terlalu berat — dari kerja, keluarga, finansial, atau kombinasi semuanya sekaligus.',
  'PTSD': 'Trauma yang kembali muncul sebagai flashback, mimpi buruk, atau respons ketakutan yang tidak proporsional dengan situasi.',
  'Pengembangan Diri': 'Mengenal diri lebih dalam, membangun kepercayaan diri, atau tumbuh jadi versi kamu yang lebih baik.',
  'Parenting': 'Tantangan mengasuh anak — komunikasi, disiplin, batasan, atau menjadi orang tua yang lebih sadar dan hadir.',
  'SAD': 'Social Anxiety Disorder — rasa takut dihakimi atau dipermalukan dalam situasi sosial, sampai akhirnya menghindari interaksi sama sekali.',
  'BDD': 'Body Dysmorphic Disorder — fokus berlebihan pada kekurangan penampilan yang mungkin tidak tampak bagi orang lain.',
  'Gangguan Kecemasan': 'Kecemasan yang sudah cukup intens dan menetap sampai mengganggu kehidupan sehari-hari.',
  'Hubungan Interpersonal': 'Kesulitan membangun atau mempertahankan hubungan yang sehat — dengan teman, keluarga, atau rekan kerja.',
  'MDD': 'Major Depressive Disorder — depresi klinis yang lebih dari sekadar sedih biasa.',
  'Gangguan Kepribadian': 'Pola pikir, perasaan, dan perilaku yang menetap dan bikin hidup terasa sulit — untuk diri sendiri maupun orang sekitar.',
  'Panic Disorder': 'Serangan panik yang muncul tiba-tiba dan intens, disertai ketakutan bahwa itu akan terjadi lagi.',
}

export const APPROACH_DEFINITIONS: Record<string, string> = {
  'CBT': 'Cognitive Behavioral Therapy — bantu kamu kenali dan ubah pola pikir yang bikin stuck, lalu ganti dengan cara merespons yang lebih sehat.',
  'ACT': 'Acceptance and Commitment Therapy — belajar menerima perasaan sulit tanpa harus melawan atau melarikan diri, supaya kamu bisa tetap gerak sesuai nilai hidup kamu.',
  'Evidence-Based': 'Menggunakan teknik-teknik yang sudah terbukti efektif secara ilmiah — bukan coba-coba.',
  'NICE Guidelines': 'Mengikuti panduan klinis NICE (UK) yang berbasis riset untuk kondisi kesehatan mental tertentu.',
  'Hipnoterapi': 'Menggunakan relaksasi dalam untuk mengakses dan mengubah pola pikir di bawah sadar.',
  'Play Therapy': 'Terapi lewat bermain — terutama untuk anak-anak yang lebih mudah mengekspresikan diri lewat permainan daripada kata-kata.',
  'Client Centered Therapy': 'Psikolog hadir sebagai teman yang mendengarkan, tanpa menghakimi. Kamu yang menentukan arahnya.',
  'Logo Therapy': 'Terapi berbasis makna hidup — mencari tujuan di balik penderitaan. Dikembangkan Viktor Frankl dari pengalamannya bertahan di kamp konsentrasi.',
  'REBT': 'Rational Emotive Behavior Therapy — identifikasi keyakinan irasional yang bikin kamu tertekan, lalu ganti dengan perspektif yang lebih realistis.',
  'Solution-Focused Behavior Therapy': 'Fokus ke solusi dan kekuatan yang sudah kamu punya — bukan menggali-gali masalah dari masa lalu.',
  'Mindfulness': 'Belajar hadir penuh di momen ini. Bukan overthinking masa lalu atau mengkhawatirkan masa depan.',
  'Mental Coaching': 'Pendekatan coaching untuk mencapai tujuan dan performa mental yang lebih optimal.',
  'NLP': 'Neuro-Linguistic Programming — menggunakan pola bahasa dan pikiran untuk mengubah perilaku dan respons emosional.',
  'Gottman Method': 'Metode berbasis riset untuk memperbaiki komunikasi dan koneksi dalam hubungan pasangan.',
  'EFT': 'Emotionally Focused Therapy — membantu memahami dan mengubah pola emosional yang bikin hubungan terasa jauh.',
  'Psychological First Aid': 'Pendekatan pertolongan pertama untuk membantu seseorang yang baru mengalami krisis atau trauma.',
  'Positive Psychotherapy': 'Fokus pada kekuatan, makna, dan hal-hal positif dalam hidup kamu — bukan hanya pada masalah.',
  'Grafologi': 'Analisis tulisan tangan sebagai salah satu alat untuk memahami kepribadian.',
  'Reconnect Compassion Therapy': 'Terapi yang berfokus pada membangun kembali koneksi dengan diri sendiri melalui rasa kasih sayang (self-compassion).',
}
